/* GENERADO AUTOMATICAMENTE por robot-nube.ps1 (API Gescom, GitHub Actions) - NO EDITAR A MANO
   Ultima actualizacion: 2026-08-04 14:04 */
window.__LPE_DATA__ = { registros: [
 {"fecha":"2026-08-03","fletero":"Claudio Garcia","repartos":1,"boletas":20,"entregadas":20,"itemsRech":0}
,{"fecha":"2026-08-03","fletero":"Diego Zacarias","repartos":1,"boletas":46,"entregadas":46,"itemsRech":0}
,{"fecha":"2026-08-03","fletero":"Emiliano Juan Amarilla","repartos":1,"boletas":16,"entregadas":16,"itemsRech":0}
,{"fecha":"2026-08-03","fletero":"Hernan Rivero","repartos":1,"boletas":22,"entregadas":22,"itemsRech":0}
,{"fecha":"2026-08-03","fletero":"Ivan Montoya","repartos":1,"boletas":25,"entregadas":25,"itemsRech":0}
,{"fecha":"2026-08-03","fletero":"Juan Escoto","repartos":1,"boletas":47,"entregadas":47,"itemsRech":0}
,{"fecha":"2026-08-03","fletero":"Leonardo Santa Cruz","repartos":1,"boletas":3,"entregadas":3,"itemsRech":0}
,{"fecha":"2026-08-03","fletero":"Mariano Sosa","repartos":1,"boletas":3,"entregadas":3,"itemsRech":0}
,{"fecha":"2026-08-03","fletero":"Miguel Angel Pallini","repartos":1,"boletas":35,"entregadas":35,"itemsRech":0}
,{"fecha":"2026-08-03","fletero":"Nahuel Montoya","repartos":2,"boletas":49,"entregadas":49,"itemsRech":0}
,{"fecha":"2026-08-03","fletero":"Simon Olivera","repartos":1,"boletas":32,"entregadas":32,"itemsRech":0}
,{"fecha":"2026-08-03","fletero":"Walter Janiuk","repartos":1,"boletas":30,"entregadas":30,"itemsRech":0}
,{"fecha":"2026-08-03","fletero":"Walter Tenore","repartos":1,"boletas":33,"entregadas":33,"itemsRech":0}
,{"fecha":"2026-08-04","fletero":"Claudio Garcia","repartos":1,"boletas":18,"entregadas":18,"itemsRech":0}
,{"fecha":"2026-08-04","fletero":"Diego Zacarias","repartos":1,"boletas":11,"entregadas":11,"itemsRech":0}
,{"fecha":"2026-08-04","fletero":"Emiliano Juan Amarilla","repartos":1,"boletas":17,"entregadas":17,"itemsRech":0}
,{"fecha":"2026-08-04","fletero":"Hernan Rivero","repartos":1,"boletas":29,"entregadas":29,"itemsRech":0}
,{"fecha":"2026-08-04","fletero":"Ivan Montoya","repartos":1,"boletas":31,"entregadas":31,"itemsRech":0}
,{"fecha":"2026-08-04","fletero":"Juan Escoto","repartos":1,"boletas":23,"entregadas":23,"itemsRech":0}
,{"fecha":"2026-08-04","fletero":"Leonardo Santa Cruz","repartos":1,"boletas":42,"entregadas":42,"itemsRech":0}
,{"fecha":"2026-08-04","fletero":"Marcelo Vacca","repartos":1,"boletas":1,"entregadas":1,"itemsRech":0}
,{"fecha":"2026-08-04","fletero":"Marcos Sanchez","repartos":1,"boletas":27,"entregadas":27,"itemsRech":0}
,{"fecha":"2026-08-04","fletero":"Mariano Sosa","repartos":2,"boletas":37,"entregadas":37,"itemsRech":0}
,{"fecha":"2026-08-04","fletero":"Miguel Angel Pallini","repartos":1,"boletas":43,"entregadas":43,"itemsRech":0}
,{"fecha":"2026-08-04","fletero":"Nahuel Montoya","repartos":1,"boletas":43,"entregadas":43,"itemsRech":0}
,{"fecha":"2026-08-04","fletero":"Simon Olivera","repartos":1,"boletas":34,"entregadas":34,"itemsRech":0}
,{"fecha":"2026-08-04","fletero":"Walter Janiuk","repartos":1,"boletas":27,"entregadas":27,"itemsRech":0}
,{"fecha":"2026-08-04","fletero":"Walter Tenore","repartos":1,"boletas":25,"entregadas":25,"itemsRech":0}
] };
window.__LPE_DATA__.empresas = [{"id":"lagopuelo","nombre":"Lago Puelo S.A.","logo":"assets/img/logo-lagopuelo.jpg","boletas":377,"rechazadas":0},{"id":"elebes","nombre":"Elebes S.A.","logo":"assets/img/logo-elebes.jpg","boletas":346,"rechazadas":0}];
window.__LPE_DATA__.clientes = {"sac":412,"ent":412};
window.__LPE_DATA__.boletasCsv = {"sac":723,"rech":0};
window.__LPE_DATA__.rechazoPlata = {"general":0,"lagopuelo":0,"elebes":0};
window.__LPE_DATA__.motivos = [];
window.__LPE_DATA__.motivosPorFletero = {};
window.__LPE_DATA__.estadisticasFletero = {"Claudio Garcia":{"cliSac":17,"cliEnt":17,"recTot":0,"compSac":38,"compEnt":38,"compRech":0,"rechImp":0},"Diego Zacarias":{"cliSac":34,"cliEnt":34,"recTot":0,"compSac":47,"compEnt":47,"compRech":0,"rechImp":0},"Emiliano Juan Amarilla":{"cliSac":22,"cliEnt":22,"recTot":0,"compSac":27,"compEnt":27,"compRech":0,"rechImp":0},"Hernan Rivero":{"cliSac":29,"cliEnt":29,"recTot":0,"compSac":51,"compEnt":51,"compRech":0,"rechImp":0},"Ivan Montoya":{"cliSac":27,"cliEnt":27,"recTot":0,"compSac":56,"compEnt":56,"compRech":0,"rechImp":0},"Juan Escoto":{"cliSac":35,"cliEnt":35,"recTot":0,"compSac":70,"compEnt":70,"compRech":0,"rechImp":0},"Leonardo Santa Cruz":{"cliSac":23,"cliEnt":23,"recTot":0,"compSac":45,"compEnt":45,"compRech":0,"rechImp":0},"Marcelo Vacca":{"cliSac":1,"cliEnt":1,"recTot":0,"compSac":1,"compEnt":1,"compRech":0,"rechImp":0},"Marcos Sanchez":{"cliSac":12,"cliEnt":12,"recTot":0,"compSac":24,"compEnt":24,"compRech":0,"rechImp":0},"Mariano Sosa":{"cliSac":20,"cliEnt":20,"recTot":0,"compSac":39,"compEnt":39,"compRech":0,"rechImp":0},"Miguel Angel Pallini":{"cliSac":54,"cliEnt":54,"recTot":0,"compSac":63,"compEnt":63,"compRech":0,"rechImp":0},"Nahuel Montoya":{"cliSac":41,"cliEnt":41,"recTot":0,"compSac":91,"compEnt":91,"compRech":0,"rechImp":0},"Simon Olivera":{"cliSac":36,"cliEnt":36,"recTot":0,"compSac":66,"compEnt":66,"compRech":0,"rechImp":0},"Walter Janiuk":{"cliSac":28,"cliEnt":28,"recTot":0,"compSac":57,"compEnt":57,"compRech":0,"rechImp":0},"Walter Tenore":{"cliSac":33,"cliEnt":33,"recTot":0,"compSac":48,"compEnt":48,"compRech":0,"rechImp":0}};
window.__LPE_DATA__.vendedoresTop = [];
window.__LPE_DATA__.proveedoresTop = [{"nombre":"MENOYO S.A.","pct":0},{"nombre":"GRUPO AYUDIN ARGENTINA S.A","pct":0},{"nombre":"CEPAS ARGENTINAS S.A","pct":0},{"nombre":"PRIMEROS PRODUCTOS PEHUENIA","pct":0},{"nombre":"SOFTYS ARGENTINA S.A","pct":0}];
window.__LPE_DATA__.proveedoresPorFletero = {"Claudio Garcia":[{"prov":"SOFTYS ARGENTINA S.A","pct":100},{"prov":"PRIMEROS PRODUCTOS PEHUENIA","pct":100},{"prov":"GRUPO AYUDIN ARGENTINA S.A","pct":100},{"prov":"CEPAS ARGENTINAS S.A","pct":100}],"Diego Zacarias":[{"prov":"ILOLAY","pct":100},{"prov":"PRIMEROS PRODUCTOS PEHUENIA","pct":100},{"prov":"GEORGALOS","pct":100},{"prov":"MENOYO S.A.","pct":100}],"Emiliano Juan Amarilla":[{"prov":"ILOLAY","pct":100},{"prov":"GEORGALOS","pct":100}],"Hernan Rivero":[{"prov":"SOFTYS ARGENTINA S.A","pct":100},{"prov":"GRUPO AYUDIN ARGENTINA S.A","pct":100},{"prov":"PORTA HNOS S.A","pct":100}],"Ivan Montoya":[{"prov":"SOFTYS ARGENTINA S.A","pct":100},{"prov":"GRUPO AYUDIN ARGENTINA S.A","pct":100},{"prov":"CEPAS ARGENTINAS S.A","pct":100}],"Juan Escoto":[{"prov":"SOFTYS ARGENTINA S.A","pct":100},{"prov":"GRUPO AYUDIN ARGENTINA S.A","pct":100},{"prov":"PRIMEROS PRODUCTOS PEHUENIA","pct":100},{"prov":"CEPAS ARGENTINAS S.A","pct":100}],"Leonardo Santa Cruz":[{"prov":"SOFTYS ARGENTINA S.A","pct":100},{"prov":"GRUPO AYUDIN ARGENTINA S.A","pct":100},{"prov":"CEPAS ARGENTINAS S.A","pct":100}],"Marcelo Vacca":[{"prov":"SOFTYS ARGENTINA S.A","pct":100}],"Marcos Sanchez":[{"prov":"PRIMEROS PRODUCTOS PEHUENIA","pct":100},{"prov":"GEORGALOS","pct":100},{"prov":"ILOLAY","pct":100}],"Mariano Sosa":[{"prov":"SOFTYS ARGENTINA S.A","pct":100},{"prov":"GRUPO AYUDIN ARGENTINA S.A","pct":100}],"Miguel Angel Pallini":[{"prov":"ILOLAY","pct":100},{"prov":"GEORGALOS","pct":100},{"prov":"MENOYO S.A.","pct":100},{"prov":"PRIMEROS PRODUCTOS PEHUENIA","pct":100},{"prov":"LCB","pct":100},{"prov":"MORIXE","pct":100}],"Nahuel Montoya":[{"prov":"SOFTYS ARGENTINA S.A","pct":100},{"prov":"ILOLAY","pct":100},{"prov":"GRUPO AYUDIN ARGENTINA S.A","pct":100},{"prov":"GEORGALOS","pct":100},{"prov":"CEPAS ARGENTINAS S.A","pct":100},{"prov":"PRIMEROS PRODUCTOS PEHUENIA","pct":100}],"Simon Olivera":[{"prov":"SOFTYS ARGENTINA S.A","pct":100},{"prov":"GRUPO AYUDIN ARGENTINA S.A","pct":100}],"Walter Janiuk":[{"prov":"SOFTYS ARGENTINA S.A","pct":100},{"prov":"GRUPO AYUDIN ARGENTINA S.A","pct":100},{"prov":"PORTA HNOS S.A","pct":100},{"prov":"CEPAS ARGENTINAS S.A","pct":100},{"prov":"MENOYO S.A.","pct":100}],"Walter Tenore":[{"prov":"GEORGALOS","pct":100},{"prov":"ILOLAY","pct":100}]};
window.__LPE_DATA__.mesAnterior = {"clave":"2026-07","anio":2026,"mes":7,"efGeneral":90.2,"empresas":[{"nombre":"Lago Puelo S.A.","ef":88},{"nombre":"Elebes S.A.","ef":90.8}],"repartos":274,"boletasEnt":6962,"boletasSac":7455,"clientesEnt":4248,"clientesSac":4485,"plataRech":46664342,"fleteros":16,"ranking":[{"nombre":"Johana Vigil","repartos":1,"ef":100},{"nombre":"Emiliano Juan Amarilla","repartos":22,"ef":95.7},{"nombre":"Luciano Gasparini","repartos":1,"ef":95.5},{"nombre":"Miguel Angel Pallini","repartos":23,"ef":94.4},{"nombre":"Walter Tenore","repartos":23,"ef":94.2},{"nombre":"Juan Escoto","repartos":19,"ef":93.3},{"nombre":"Nahuel Montoya","repartos":17,"ef":92.2},{"nombre":"Diego Zacarias","repartos":23,"ef":91.7},{"nombre":"Marcos Sanchez","repartos":23,"ef":91.3},{"nombre":"Claudio Garcia","repartos":20,"ef":87.8},{"nombre":"Mariano Sosa","repartos":18,"ef":87.7},{"nombre":"Ivan Montoya","repartos":17,"ef":87.2},{"nombre":"Walter Janiuk","repartos":17,"ef":86.5},{"nombre":"Leonardo Santa Cruz","repartos":17,"ef":86.2},{"nombre":"Hernan Rivero","repartos":17,"ef":84.8},{"nombre":"Simon Olivera","repartos":16,"ef":84}]};
